### ISSUE TITLE
Not Work AnyMore

### ISSUE THREAD

**Issue by kokoboko5** [n0x073/CR-dl#10]
When I download this message appears

SyntaxError: Unexpected token , in JSON at position 2
    at JSON.parse (<anonymous>)
    at VilosVideoInfo.<anonymous> (C:\snapshot\CR-dl\lib\api\MediaVilosPlayer.js:198:57)
    at Generator.next (<anonymous>)
    at C:\snapshot\CR-dl\lib\api\MediaVilosPlayer.js:27:71
    at new Promise (<anonymous>)
    at C:\snapshot\CR-dl\lib\api\MediaVilosPlayer.js:23:12
    at VilosVideoInfo.getSeasonTitle (C:\snapshot\CR-dl\lib\api\MediaVilosPlayer.js:196:16)
    at C:\snapshot\CR-dl\lib\commands\cr-dl-download.js:238:42
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\CR-dl\lib\commands\cr-dl-download.js:25:58)

**Comment by Tizioincognit0** [comment]
I'd had the same problem but I fixed it replacing the line 198 of the file @n0x073/cr-dl/lib/api/MediaVilosPlayer.js with the following code: `const seasonTitle = "One Piece"`. Obviously it's a temporary fix and all your downloads will have "One Piece" in the filename. You can replace "One Piece" with any string.

**Comment by UA3** [comment]
Thanks for the tip @Tizioincognit0 !! the workaround for the filename is to specify a custom name for the seasonTitle, by including the show name instead of {seasonTitle}, example: `-o "[MySubs] OnePiece - {episodeNumber} [{resolution}].mkv"`

**Comment by fidodone** [comment]
Same problem here :/
Even with @UA3 tip didn't work
![image](https://user-images.githubusercontent.com/30482835/107268665-40e5c180-6a27-11eb-9bc1-9a5bdbe55d13.png)

**Comment by UA3** [comment]
@fidodone Did you changed to a constant value like @Tizioincognit0 suggested? my tip is only for naming the output file after you change line 198 in `/snapshot/cr-dl/lib/api/MediaVilosPlayer.js`

**Comment by fidodone** [comment]
> 
> 
> I've the same problem but I fixed it replacing the line 198 of the file @n0x073/cr-dl/lib/api/MediaVilosPlayer.js with the following code: `const seasonTitle = "One Piece"`. Obviously it's a temporary fix and all your downloads will have "One Piece" in the filename. You can replace "One Piece" with any string.



> 
> 
> I'd had the same problem but I fixed it replacing the line 198 of the file @n0x073/cr-dl/lib/api/MediaVilosPlayer.js with the following code: `const seasonTitle = "One Piece"`. Obviously it's a temporary fix and all your downloads will have "One Piece" in the filename. You can replace "One Piece" with any string.

Where do I find this file? I'm using the pre-build version for linux

**Comment by fidodone** [comment]
> 
> 
> @fidodone Did you changed to a constant value like @Tizioincognit0 suggested? my tip is only for naming the output file after you change line 198 in `/snapshot/cr-dl/lib/api/MediaVilosPlayer.js`

Where do I find this file? I'm using the pre-build version for linux

**Comment by UA3** [comment]
Did you try the path I mentioned?

`/snapshot/cr-dl/lib/api/MediaVilosPlayer.js`

**Comment by fidodone** [comment]
> 
> 
> Did you try the path I mentioned?
> 
> `/snapshot/cr-dl/lib/api/MediaVilosPlayer.js`

yes, but this folder doesn't exist here on my system

what system are you using? and how did you install the cr-dl?

I just extracted the zip for linux and ran from there

**Comment by UA3** [comment]
I installed it using `npm install -g @n0x073/cr-dl` in macOS, the file was in this path `/usr/local/lib/node_modules/@n0x073/cr-dl/lib/api`

Try to install using npm, the file location will be displayed in the error message.

**Comment by fidodone** [comment]
> 
> 
> I installed it using `npm install -g @n0x073/cr-dl` in macOS, the file was in this path `/usr/local/lib/node_modules/@n0x073/cr-dl/lib/api`
> 
> Try to install using npm, the file location will be displayed in the error message.

Thaaaaannnk's, it worked

**Comment by vicentehenrique1998** [comment]
Does anyone know how to resolve this problem on windows 10?

**Comment by Tizioincognit0** [comment]
> Does anyone know how to resolve this problem on windows 10?

If you're on Windows 10, I suggest you to use this GUI app instead: https://github.com/hama3254/Crunchyroll-Downloader-v3.0.
