### ISSUE TITLE
I'm being temporarily banned from Crunchyroll

### ISSUE THREAD

**Issue by vicentehenrique1998** [n0x073/CR-dl#5]
I'm being banned from Crunchyroll by downloading only one subtitle per episode, only subtitles. The ban lasts a few hours. 
This appears in the CMD:
Error: Couldn't find video config on webpage.
    at new VilosVideoInfo (C:\snapshot\CR-dl\lib\api\MediaVilosPlayer.js:102:19)
    at CrDl.<anonymous> (C:\snapshot\CR-dl\lib\api\CrDl.js:181:20)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\CR-dl\lib\api\CrDl.js:5:58)

And it appears on Crunchyroll:

Error 1015 Ray ID: 5f60a6c96d6509f4 • 2020-11-22 06:39:07 UTC
You are being rate limited
What happened?
The owner of this website (www.crunchyroll.com) has banned you temporarily from accessing this website.

**Comment by n0x073** [comment]
Does this still appears and how many subtitles did you download?

If you produce too much traffic, they can block you, thats not a problem with crdl i think.
but it happens only downloading 1 file i will inspect your problem.

**Comment by vicentehenrique1998** [comment]
It happens when I download only one subtitle for each episode of a show and only the subtitle, without the video. I think it is because of many requests in a short period of time, the subtitles download very quickly. If you have how to make a timer between downloads, should resolve.
